#define CEC_OP_USER_CONTROL_PRESSED  0x44
#define CEC_OP_USER_CONTROL_RELEASED 0x45

#define CEC_KEY_SELECT               0x00
#define CEC_KEY_UP                   0x01
#define CEC_KEY_DOWN                 0x02
#define CEC_KEY_LEFT                 0x03
#define CEC_KEY_RIGHT                0x04
#define CEC_KEY_RIGHT_UP             0x05
#define CEC_KEY_RIGHT_DOWN           0x06
#define CEC_KEY_LEFT_UP              0x07
#define CEC_KEY_LEFT_DOWN            0x08
#define CEC_KEY_ROOT_MENU            0x09
#define CEC_KEY_SETUP_MENU           0x0A
#define CEC_KEY_CONTENTS_MENU        0x0B
#define CEC_KEY_FAVORITE_MENU        0x0C
#define CEC_KEY_EXIT                 0x0D
#define CEC_KEY_0                    0x20
#define CEC_KEY_1                    0x21
#define CEC_KEY_2                    0x22
#define CEC_KEY_3                    0x23
#define CEC_KEY_4                    0x24
#define CEC_KEY_5                    0x25
#define CEC_KEY_6                    0x26
#define CEC_KEY_7                    0x27
#define CEC_KEY_8                    0x28
#define CEC_KEY_9                    0x29
#define CEC_KEY_DOT                  0x2A
#define CEC_KEY_ENTER                0x2B
#define CEC_KEY_CLEAR                0x2C
#define CEC_KEY_NEXT_FAVORITE        0x2F
#define CEC_KEY_CHANNEL_UP           0x30
#define CEC_KEY_CHANNEL_DOWN         0x31
#define CEC_KEY_CHANNEL_PREV         0x32
#define CEC_KEY_SOUND_SELECT         0x33
#define CEC_KEY_INPUT_SELECT         0x34
#define CEC_KEY_DISPLAY_INFO         0x35
#define CEC_KEY_HELP                 0x36
#define CEC_KEY_PAGE_UP              0x37
#define CEC_KEY_PAGE_DOWN            0x38
#define CEC_KEY_POWER                0x40
#define CEC_KEY_VOLUME_UP            0x41
#define CEC_KEY_VOLUME_DOWN          0x42
#define CEC_KEY_MUTE                 0x43
#define CEC_KEY_PLAY                 0x44
#define CEC_KEY_STOP                 0x45
#define CEC_KEY_PAUSE                0x46
#define CEC_KEY_RECORD               0x47
#define CEC_KEY_REWIND               0x48
#define CEC_KEY_FAST_FORWARD         0x49
#define CEC_KEY_EJECT                0x4A
#define CEC_KEY_FORWARD              0x4B
#define CEC_KEY_BACKWARD             0x4C
#define CEC_KEY_STOP_RECORD          0x4D
#define CEC_KEY_PAUSE_RECORD         0x4E
#define CEC_KEY_ANGLE                0x50
#define CEC_KEY_SUB_PICTURE          0x51
#define CEC_KEY_VIDEO_ON_DEMAND      0x52
#define CEC_KEY_EPG                  0x53
#define CEC_KEY_TIMER_PROG           0x54
#define CEC_KEY_INITIAL_CONFIG       0x55
#define CEC_KEY_PLAY_FUNC            0x60
#define CEC_KEY_PAUSE_PLAY_FUNC      0x61
#define CEC_KEY_RECORD_FUNC          0x62
#define CEC_KEY_PAUSE_RECORD_FUNC    0x63
#define CEC_KEY_STOP_FUNC            0x64
#define CEC_KEY_MUTE_FUNC            0x65
#define CEC_KEY_RESTORE_COLUME_FUNC  0x66
#define CEC_KEY_TUNE_FUNC            0x67
#define CEC_KEY_SELECT_MEDIA_FUNC    0x68
#define CEC_KEY_SELECT_AV_INPUT_FUNC 0x69
#define CEC_KEY_SELECT_AUDIO_INPUT_FUNC 0x6A
#define CEC_KEY_POWER_TOGGLE_FUNC    0x6B
#define CEC_KEY_POWER_OFF_FUNC       0x6C
#define CEC_KEY_POWER_ON_FUNC        0x6D
#define CEC_KEY_F1_BLUE              0x71
#define CEC_KEY_F2_RED               0x72
#define CEC_KEY_F3_GREEN             0x73
#define CEC_KEY_F4_YELLOW            0x74
#define CEC_KEY_F5                   0x75
#define CEC_KEY_DATA                 0x76

